name: Action CI / Nix

on:
  pull_request:
    branches:
      - '*'

jobs:
  nix-shell-build:
    name: Build Nix Shell
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          determinate: true
      - name: FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@v1
      - name: Build
        run: nix-build shell.nix
