name: Action CI

on:
  pull_request_target:
    branches:
      - '*'

jobs:
  upload-log:
    name: Upload to R2 - Log File
    
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        node-version: ["lts/*"]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Create test file
        run: |
          mkdir tests/log
          echo Upload test - ${{ steps.date.outputs.date }} > "tests/log/upload-${{ steps.date.outputs.date }}"
      - name: Upload to R2
        uses: ./
        with:
          r2-account-id: ${{ secrets.TEST_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.TEST_R2_AKID }}
          r2-secret-access-key: ${{ secrets.TEST_R2_SECRET_AK }}
          r2-bucket: ${{ secrets.TEST_R2_BUCKET }}
          source-dir: tests/log
          destination-dir: r2-upload-action/test-logs